version: '3'

services:
  db:
    image: postgres:14.5
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: fastapi-app
    network_mode: host
    env_file:
      - ./.env
    depends_on:
      - db
    environment:
      WAIT_HOSTS: localhost:5432