version: '3'

services:
  db:
    image: postgres:14.5
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  cache:
    image: redis:6.2
    restart: always
    env_file:
      - ./.env
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
  s3:
    image: quay.io/minio/minio
    env_file:
      - ./.env
    volumes:
      - /minio/data:/data
    network_mode: host
    ports:
      - "9000:9000"
      - "9090:9090"
    command: server --console-address ":9090" /data

  backend:
    build: .
    container_name: fastapi-app
    network_mode: host
    env_file:
      - ./.env
    depends_on:
      - db
      - cache
      - s3

volumes:
  redis_data:
  minio_data: