version: '3'

services:
  db:
    image: postgres:14.5
    restart: on-failure
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks:
      custom:

  cache:
    image: redis:6.2
    restart: on-failure
    env_file:
      - ./.env
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      custom:

  s3:
    image: quay.io/minio/minio
    env_file:
      - ./.env
    ports:
      - "9000:9000"
      - "9090:9090"
    command: server --console-address ":9090" /data
    networks:
      custom:

  app:
    build: .
    container_name: fastapi-app
    restart: on-failure
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
      - cache
      - s3
    networks:
      custom:

  web:
    container_name: web
    restart: on-failure
    image: nginx:alpine
    ports:
      - "8082:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      custom:


volumes:
  redis_data:

networks:
  custom:
    driver: bridge