version: '3'

services:
  db:
    image: postgres:14.5
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  cache:
    image: redis:6.2
    restart: always
    env_file:
      - ./.env
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: fastapi-app
    network_mode: host
    env_file:
      - ./.env
    depends_on:
      - db
      - cache

volumes:
  redis_data: